package BankApp;


/**
* BankApp/_AccountImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public abstract class _AccountImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements BankApp.Account, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AccountImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("withDraw", new java.lang.Integer (0));
    _methods.put ("deposit", new java.lang.Integer (1));
    _methods.put ("balanceQuery", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankApp/Account/withDraw
       {
         float amt = in.read_float ();
         String acctno = in.read_string ();
         int $result = (int)0;
         $result = this.withDraw (amt, acctno);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // BankApp/Account/deposit
       {
         float amt = in.read_float ();
         String acctno = in.read_string ();
         int $result = (int)0;
         $result = this.deposit (amt, acctno);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  //AcctDetails getAcctDetails(in string acctno);
       case 2:  // BankApp/Account/balanceQuery
       {
         String acctno = in.read_string ();
         float $result = (float)0;
         $result = this.balanceQuery (acctno);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankApp/Account:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AccountImplBase
