package BankApp;


/**
* BankApp/_BankImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public abstract class _BankImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements BankApp.Bank, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _BankImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createAccount", new java.lang.Integer (0));
    _methods.put ("getAccount", new java.lang.Integer (1));
    _methods.put ("login", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankApp/Bank/createAccount
       {
         String accountid = in.read_string ();
         String password = in.read_string ();
         String initBalance = in.read_string ();
         String custname = in.read_string ();
         String city = in.read_string ();
         String acctType = in.read_string ();
         int $result = (int)0;
         $result = this.createAccount (accountid, password, initBalance, custname, city, acctType);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // BankApp/Bank/getAccount
       {
         String acctno = in.read_string ();
         BankApp.Account $result = null;
         $result = this.getAccount (acctno);
         out = $rh.createReply();
         BankApp.AccountHelper.write (out, $result);
         break;
       }


  //Customer getCustomer(in string acctno);
       case 2:  // BankApp/Bank/login
       {
         String uname = in.read_string ();
         String passwd = in.read_string ();
         int $result = (int)0;
         $result = this.login (uname, passwd);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankApp/Bank:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _BankImplBase
