package BankApp;


/**
* BankApp/_CustomerImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public abstract class _CustomerImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements BankApp.Customer, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CustomerImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCustDetails", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankApp/Customer/getCustDetails
       {
         String acctno = in.read_string ();
         BankApp.CustDetails $result = null;
         $result = this.getCustDetails (acctno);
         out = $rh.createReply();
         BankApp.CustDetailsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankApp/Customer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CustomerImplBase
