package BankApp;


/**
* BankApp/_CustomerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public class _CustomerStub extends org.omg.CORBA.portable.ObjectImpl implements BankApp.Customer
{

  public BankApp.CustDetails getCustDetails (String acctno)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCustDetails", true);
                $out.write_string (acctno);
                $in = _invoke ($out);
                BankApp.CustDetails $result = BankApp.CustDetailsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCustDetails (acctno        );
            } finally {
                _releaseReply ($in);
            }
  } // getCustDetails

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankApp/Customer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _CustomerStub
