package BankApp;


/**
* BankApp/AcctDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public final class AcctDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String acctType = null;
  public String acctno = null;
  public float balance = (float)0;

  public AcctDetails ()
  {
  } // ctor

  public AcctDetails (String _acctType, String _acctno, float _balance)
  {
    acctType = _acctType;
    acctno = _acctno;
    balance = _balance;
  } // ctor

} // class AcctDetails
