package BankApp;

/**
* BankApp/AcctDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public final class AcctDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public BankApp.AcctDetails value = null;

  public AcctDetailsHolder ()
  {
  }

  public AcctDetailsHolder (BankApp.AcctDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankApp.AcctDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankApp.AcctDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankApp.AcctDetailsHelper.type ();
  }

}
