package BankApp;


/**
* BankApp/BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public interface BankOperations 
{
  int createAccount (String accountid, String password, String initBalance, String custname, String city, String acctType);
  BankApp.Account getAccount (String acctno);

  //Customer getCustomer(in string acctno);
  int login (String uname, String passwd);
} // interface BankOperations
