package BankApp;

/**
* BankApp/BankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public final class BankHolder implements org.omg.CORBA.portable.Streamable
{
  public BankApp.Bank value = null;

  public BankHolder ()
  {
  }

  public BankHolder (BankApp.Bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankApp.BankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankApp.BankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankApp.BankHelper.type ();
  }

}
