package BankApp;


/**
* BankApp/Bank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public interface Bank extends BankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bank
