package BankApp;


/**
* BankApp/CustomerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public interface CustomerOperations 
{
  BankApp.CustDetails getCustDetails (String acctno);
} // interface CustomerOperations
