package BankApp;


/**
* BankApp/CustDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public final class CustDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String city = null;
  public String acctno = null;

  public CustDetails ()
  {
  } // ctor

  public CustDetails (String _name, String _city, String _acctno)
  {
    name = _name;
    city = _city;
    acctno = _acctno;
  } // ctor

} // class CustDetails
