package BankApp;

/**
* BankApp/CustomerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public final class CustomerHolder implements org.omg.CORBA.portable.Streamable
{
  public BankApp.Customer value = null;

  public CustomerHolder ()
  {
  }

  public CustomerHolder (BankApp.Customer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankApp.CustomerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankApp.CustomerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankApp.CustomerHelper.type ();
  }

}
