package BankApp;

/**
* BankApp/CustDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from banker.idl
* Friday, June 18, 2004 8:45:41 PM IST
*/

public final class CustDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public BankApp.CustDetails value = null;

  public CustDetailsHolder ()
  {
  }

  public CustDetailsHolder (BankApp.CustDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankApp.CustDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankApp.CustDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankApp.CustDetailsHelper.type ();
  }

}
